import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald} from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/componets/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald=Oswald({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "FitLog-- Workout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${oswald.className}h-full antialiased bg-[#0C0D10]`}
    >
      <body className="min-h-full flex flex-col ">
        <Navbar/>
        
        {children}
        <ToastContainer />
        
        </body>

      
    </html>
  );
}
